// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/reports" | "/auth/sign-in" | "/garden" | "/me" | "/notifications" | "/onboarding" | "/pets/[petId]" | "/pets/new" | "/plaza" | "/posts/[postId]"
type AppRouteHandlerRoutes = "/api/admin/garden/tick" | "/api/admin/reports" | "/api/admin/reports/[reportId]/resolve" | "/api/auth/magic-link" | "/api/auth/sign-out" | "/api/chat/[petId]" | "/api/chat/[petId]/stream" | "/api/garden/encounters/[threadId]/actions" | "/api/garden/events-stream" | "/api/garden/ledger" | "/api/garden/narrate" | "/api/garden/objects/clean" | "/api/garden/presence" | "/api/garden/snapshot" | "/api/home/signals" | "/api/me/pets/status" | "/api/notifications" | "/api/pets" | "/api/pets/[petId]/actions" | "/api/pets/[petId]/generations" | "/api/pets/[petId]/inner-voice" | "/api/pets/[petId]/journal" | "/api/pets/[petId]/memory" | "/api/pets/[petId]/play-requests" | "/api/pets/[petId]/refresh-profile" | "/api/pets/[petId]/social-chat" | "/api/pets/[petId]/source-photo" | "/api/play-requests/[id]/respond" | "/api/plaza" | "/api/posts" | "/api/posts/[postId]/comments" | "/api/posts/[postId]/reactions" | "/api/profile" | "/api/reports" | "/api/webhooks/image-generation" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin/reports": {}
  "/api/admin/garden/tick": {}
  "/api/admin/reports": {}
  "/api/admin/reports/[reportId]/resolve": { "reportId": string; }
  "/api/auth/magic-link": {}
  "/api/auth/sign-out": {}
  "/api/chat/[petId]": { "petId": string; }
  "/api/chat/[petId]/stream": { "petId": string; }
  "/api/garden/encounters/[threadId]/actions": { "threadId": string; }
  "/api/garden/events-stream": {}
  "/api/garden/ledger": {}
  "/api/garden/narrate": {}
  "/api/garden/objects/clean": {}
  "/api/garden/presence": {}
  "/api/garden/snapshot": {}
  "/api/home/signals": {}
  "/api/me/pets/status": {}
  "/api/notifications": {}
  "/api/pets": {}
  "/api/pets/[petId]/actions": { "petId": string; }
  "/api/pets/[petId]/generations": { "petId": string; }
  "/api/pets/[petId]/inner-voice": { "petId": string; }
  "/api/pets/[petId]/journal": { "petId": string; }
  "/api/pets/[petId]/memory": { "petId": string; }
  "/api/pets/[petId]/play-requests": { "petId": string; }
  "/api/pets/[petId]/refresh-profile": { "petId": string; }
  "/api/pets/[petId]/social-chat": { "petId": string; }
  "/api/pets/[petId]/source-photo": { "petId": string; }
  "/api/play-requests/[id]/respond": { "id": string; }
  "/api/plaza": {}
  "/api/posts": {}
  "/api/posts/[postId]/comments": { "postId": string; }
  "/api/posts/[postId]/reactions": { "postId": string; }
  "/api/profile": {}
  "/api/reports": {}
  "/api/webhooks/image-generation": {}
  "/auth/callback": {}
  "/auth/sign-in": {}
  "/garden": {}
  "/me": {}
  "/notifications": {}
  "/onboarding": {}
  "/pets/[petId]": { "petId": string; }
  "/pets/new": {}
  "/plaza": {}
  "/posts/[postId]": { "postId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
