// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../../app/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/sign-in">> = Specific
  const handler = {} as typeof import("../../../app/auth/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/garden/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/garden">> = Specific
  const handler = {} as typeof import("../../../app/garden/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/me/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/me">> = Specific
  const handler = {} as typeof import("../../../app/me/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../../app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../../app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pets/[petId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pets/[petId]">> = Specific
  const handler = {} as typeof import("../../../app/pets/[petId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pets/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pets/new">> = Specific
  const handler = {} as typeof import("../../../app/pets/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/plaza/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/plaza">> = Specific
  const handler = {} as typeof import("../../../app/plaza/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/posts/[postId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/posts/[postId]">> = Specific
  const handler = {} as typeof import("../../../app/posts/[postId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/garden/tick/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/garden/tick">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/garden/tick/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/reports/[reportId]/resolve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports/[reportId]/resolve">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/reports/[reportId]/resolve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/magic-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/magic-link">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/magic-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/sign-out/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/sign-out">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/sign-out/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chat/[petId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/[petId]">> = Specific
  const handler = {} as typeof import("../../../app/api/chat/[petId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chat/[petId]/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/[petId]/stream">> = Specific
  const handler = {} as typeof import("../../../app/api/chat/[petId]/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/garden/encounters/[threadId]/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/garden/encounters/[threadId]/actions">> = Specific
  const handler = {} as typeof import("../../../app/api/garden/encounters/[threadId]/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/garden/events-stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/garden/events-stream">> = Specific
  const handler = {} as typeof import("../../../app/api/garden/events-stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/garden/ledger/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/garden/ledger">> = Specific
  const handler = {} as typeof import("../../../app/api/garden/ledger/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/garden/narrate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/garden/narrate">> = Specific
  const handler = {} as typeof import("../../../app/api/garden/narrate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/garden/objects/clean/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/garden/objects/clean">> = Specific
  const handler = {} as typeof import("../../../app/api/garden/objects/clean/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/garden/presence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/garden/presence">> = Specific
  const handler = {} as typeof import("../../../app/api/garden/presence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/garden/snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/garden/snapshot">> = Specific
  const handler = {} as typeof import("../../../app/api/garden/snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/home/signals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/home/signals">> = Specific
  const handler = {} as typeof import("../../../app/api/home/signals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/me/pets/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/pets/status">> = Specific
  const handler = {} as typeof import("../../../app/api/me/pets/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../../app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pets/[petId]/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pets/[petId]/actions">> = Specific
  const handler = {} as typeof import("../../../app/api/pets/[petId]/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pets/[petId]/generations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pets/[petId]/generations">> = Specific
  const handler = {} as typeof import("../../../app/api/pets/[petId]/generations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pets/[petId]/inner-voice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pets/[petId]/inner-voice">> = Specific
  const handler = {} as typeof import("../../../app/api/pets/[petId]/inner-voice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pets/[petId]/journal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pets/[petId]/journal">> = Specific
  const handler = {} as typeof import("../../../app/api/pets/[petId]/journal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pets/[petId]/memory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pets/[petId]/memory">> = Specific
  const handler = {} as typeof import("../../../app/api/pets/[petId]/memory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pets/[petId]/play-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pets/[petId]/play-requests">> = Specific
  const handler = {} as typeof import("../../../app/api/pets/[petId]/play-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pets/[petId]/refresh-profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pets/[petId]/refresh-profile">> = Specific
  const handler = {} as typeof import("../../../app/api/pets/[petId]/refresh-profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pets/[petId]/social-chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pets/[petId]/social-chat">> = Specific
  const handler = {} as typeof import("../../../app/api/pets/[petId]/social-chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pets/[petId]/source-photo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pets/[petId]/source-photo">> = Specific
  const handler = {} as typeof import("../../../app/api/pets/[petId]/source-photo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pets">> = Specific
  const handler = {} as typeof import("../../../app/api/pets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/play-requests/[id]/respond/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/play-requests/[id]/respond">> = Specific
  const handler = {} as typeof import("../../../app/api/play-requests/[id]/respond/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/plaza/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plaza">> = Specific
  const handler = {} as typeof import("../../../app/api/plaza/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/posts/[postId]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts/[postId]/comments">> = Specific
  const handler = {} as typeof import("../../../app/api/posts/[postId]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/posts/[postId]/reactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts/[postId]/reactions">> = Specific
  const handler = {} as typeof import("../../../app/api/posts/[postId]/reactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts">> = Specific
  const handler = {} as typeof import("../../../app/api/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile">> = Specific
  const handler = {} as typeof import("../../../app/api/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/webhooks/image-generation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/image-generation">> = Specific
  const handler = {} as typeof import("../../../app/api/webhooks/image-generation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
