var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/garden/events-stream/route.js")
R.c("server/chunks/[root-of-the-server]__d3313b6e._.js")
R.c("server/chunks/node_modules_next_c16ecf7b._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_7e8f41ca._.js")
R.c("server/chunks/node_modules_zod_v4_da12b5b3._.js")
R.c("server/chunks/node_modules_tailwind-merge_dist_bundle-mjs_mjs_c3b2c59f._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_02e1b12e._.js")
R.c("server/chunks/[root-of-the-server]__d6fda29d._.js")
R.c("server/chunks/_next-internal_server_app_api_garden_events-stream_route_actions_df0a94ab.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/garden/events-stream/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/garden/events-stream/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
