var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/magic-link/route.js")
R.c("server/chunks/[root-of-the-server]__0eb6df84._.js")
R.c("server/chunks/node_modules_next_ece99f70._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_7e8f41ca._.js")
R.c("server/chunks/node_modules_zod_v4_da12b5b3._.js")
R.c("server/chunks/node_modules_tailwind-merge_dist_bundle-mjs_mjs_c3b2c59f._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_02e1b12e._.js")
R.c("server/chunks/[root-of-the-server]__d6fda29d._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_magic-link_route_actions_ddfdce57.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/auth/magic-link/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/auth/magic-link/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
